TRUNCATE TABLE payment RESTART IDENTITY CASCADE;
TRUNCATE TABLE ticket RESTART IDENTITY CASCADE;
TRUNCATE TABLE cinema_session RESTART IDENTITY CASCADE;
TRUNCATE TABLE hall RESTART IDENTITY CASCADE;
TRUNCATE TABLE movie RESTART IDENTITY CASCADE;
TRUNCATE TABLE genre RESTART IDENTITY CASCADE;
TRUNCATE TABLE app_user RESTART IDENTITY CASCADE;
TRUNCATE TABLE role RESTART IDENTITY CASCADE;

TRUNCATE TABLE databasechangelog;
TRUNCATE TABLE databasechangeloglock;
